### ISSUE TITLE
Library file miss

### ISSUE THREAD

**Issue by JamesLiu007** [Beckhoff-USA-Community/ScopeServerControlExample#1]
![image](https://github.com/Beckhoff-USA-Community/ScopeServerControlExample/assets/41882289/d3c82108-8804-4d21-9171-383b5f814592)
The lib file 'Data Generation' needs to be added to the repository

**Comment by andrea7376** [comment]
I got the same problem.
Please the FB_GenerateData is needed to run the sample, thanks.

**Comment by MattKlev** [comment]
Fixed. 
Replaced the library with a library that is included with the TwinCAT installation.
